### ISSUE TITLE
an error i get

### ISSUE THREAD

**Issue by asmcad** [eklitzke/schemaless#3]
when i run this : python mysqlbench.py bench.yaml

i get this error : 

Traceback (most recent call last):
  File "mysqlbench.py", line 180, in <module>
    main(opts, args)
  File "mysqlbench.py", line 113, in main
    conn = MySQLdb.connect(*_cfg)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/**init**.py", line 81, in Connect
    return Connection(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in **init**
    super(Connection, self).**init**(_args, **kwargs2)
TypeError: connect() argument 3 must be string, not None
serdem@ubuntu:~/ff/examples/mysqlbench$ 

what am i doing wrong?

thanks 
serdem

**Comment by asmcad** [comment]
also there is problem with orm.guid() function. i'm not sure what it is.
